import json
import os
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def generate_compliance_report(scan_results_path: str, output_path: str = None):
    with open(scan_results_path, "r") as f:
        packets = json.load(f)

    violations = [p for p in packets if p.get("pci_violation")]
    total_packets = len(packets)
    total_violations = len(violations)
    violation_rate = round((total_violations / total_packets * 100), 1) if total_packets > 0 else 0

    violation_types = list(set([
        p["violation_detail"] for p in violations
        if p.get("violation_detail")
    ]))

    affected_ips = list(set([
        p["src_ip"] for p in violations
        if p.get("src_ip")
    ]))

    if total_violations == 0:
        overall_status = "COMPLIANT"
    elif total_violations < 5:
        overall_status = "NON-COMPLIANT - LOW RISK"
    elif total_violations < 20:
        overall_status = "NON-COMPLIANT - MEDIUM RISK"
    else:
        overall_status = "NON-COMPLIANT - HIGH RISK"

    scan_start = packets[0]["timestamp"] if packets else "N/A"
    scan_end = packets[-1]["timestamp"] if packets else "N/A"

    report = f"""
================================================================================
                    MAX-GUARD PCI-DSS COMPLIANCE REPORT
                         Powered by GPT-4o-mini AI Analysis
================================================================================

REPORT METADATA
---------------
Generated By:      Max-Guard v1.0
Report Date:       {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Scan Period:       {scan_start} to {scan_end}
Organization:      Central Connecticut State University - Retail Lab
Assessed By:       Ahmad Alkhoudeir (Security Lead)
Report Type:       PCI-DSS v4.0 Network Security Assessment

================================================================================
EXECUTIVE SUMMARY
================================================================================

Overall Compliance Status: {overall_status}

This report presents the findings of an automated network security scan
performed using Max-Guard, an AI-driven PCI-DSS compliance scanner. The scan
analyzed network traffic for violations of PCI-DSS v4.0 requirements, focusing
on unencrypted protocol usage in a simulated retail environment.

Key Findings:
  - Total Packets Analyzed:    {total_packets}
  - Total Violations Detected: {total_violations}
  - Violation Rate:            {violation_rate}%
  - Affected Devices:          {len(affected_ips)}
  - Unique Violation Types:    {len(violation_types)}

================================================================================
SCOPE OF ASSESSMENT
================================================================================

Network Segments Scanned:
  - Retail lab network (VMware Host-only: 192.168.116.0/24)
  - Simulated POS Terminal: 192.168.116.129
  - Simulated Database Server: 192.168.116.130
  - Max-Guard Scanner: 192.168.116.128

PCI-DSS Requirements Assessed:
  - Requirement 1.3.2: Restrict inbound and outbound traffic
  - Requirement 4.2.1: Strong cryptography for data in transit
  - Requirement 6.4.1: Public-facing web applications protection
  - Requirement 8.3.1: Strong authentication for all users

================================================================================
VIOLATIONS FOUND
================================================================================

"""
    if violations:
        for i, v_type in enumerate(violation_types, 1):
            v_packets = [p for p in violations if p.get("violation_detail") == v_type]
            report += f"""Violation {i}: {v_type}
  Occurrences:  {len(v_packets)}
  Source IPs:   {list(set([p['src_ip'] for p in v_packets]))}
  First Seen:   {v_packets[0]['timestamp']}
  Last Seen:    {v_packets[-1]['timestamp']}
  Severity:     CRITICAL
  Status:       FAIL

"""
    else:
        report += "  No violations detected. Network is PCI-DSS compliant.\n\n"

    report += f"""================================================================================
AFFECTED DEVICES
================================================================================

"""
    for ip in affected_ips:
        ip_violations = [p for p in violations if p.get("src_ip") == ip]
        report += f"""Device IP: {ip}
  Total Violations: {len(ip_violations)}
  Violation Types:  {list(set([p['violation_detail'] for p in ip_violations]))}

"""

    report += f"""================================================================================
REMEDIATION REQUIREMENTS
================================================================================

The following actions are required to achieve PCI-DSS v4.0 compliance:

1. IMMEDIATE (Within 24 hours):
   - Disable all Telnet services and replace with SSH v2
   - Block ports 21, 23, 80 at the network firewall
   - Isolate all affected devices pending remediation

2. SHORT TERM (Within 7 days):
   - Implement HTTPS on all web-facing services
   - Deploy SFTP or FTPS to replace FTP
   - Conduct full network audit for additional violations
   - Update network security policies

3. LONG TERM (Within 30 days):
   - Implement continuous network monitoring
   - Deploy intrusion detection system (IDS)
   - Conduct PCI-DSS v4.0 staff training
   - Schedule quarterly compliance scans

================================================================================
COMPLIANCE SUMMARY
================================================================================

PCI-DSS Requirement 1.3.2:  {'FAIL' if any('RDP' in str(v) for v in violation_types) else 'PASS'}
PCI-DSS Requirement 4.2.1:  {'FAIL' if any(v for v in violation_types if 'Unencrypted' in str(v)) else 'PASS'}
PCI-DSS Requirement 6.4.1:  {'FAIL' if any('HTTP' in str(v) for v in violation_types) else 'PASS'}

Overall Assessment: {overall_status}

================================================================================
DISCLAIMER
================================================================================

This assessment was conducted using Max-Guard v1.0 for academic purposes at
Central Connecticut State University. All scanning was performed exclusively
on owned and authorized networks. This report is for educational use only.

Max-Guard | CCSU Cybersecurity Project | May 2026
================================================================================
"""

    if output_path is None:
        output_path = f"maxguard_compliance_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt"

    with open(output_path, "w") as f:
        f.write(report)

    print(f"Compliance report generated: {output_path}")
    return report

if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1:
        scan_file = sys.argv[1]
    else:
        scan_file = "scan_results.json"

    if os.path.exists(scan_file):
        report = generate_compliance_report(scan_file)
        print(report)
    else:
        print(f"Error: {scan_file} not found. Run a scan first.")