import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import json
import os
import sys
import csv
import io
from datetime import datetime
from dotenv import load_dotenv
if 'result' not in st.session_state:
    try:
        with open ('scan_results.json', 'r') as f:
            st.session_state.result = json.load(f)
    except FileNotFoundError:
        st.session_state.result = {"analysis": "Waiting for scan...."}
if "latest_analysis" not in st.session_state:
    st.session_state.latest_analysis = None
if "latest_packets" not in st.session_state:
    st.session_state.latest_packets = None
if "latest_voice_text" not in st.session_state:
    st.session_state.latest_voice_text = ""
if "latest_voice_audio" not in st.session_state:
    st.session_state.latest_voice_audio = None
if "latest_scan_meta" not in st.session_state:
    st.session_state.latest_scan_meta = None
    
def listen_for_command():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        st.info("Listening for command....")
        r.adjust_for_ambient_noise(source, duration=1)
        audio = r.listen(source)
    try:
        command = r.recognize_google(audio)
        return command.lower()
    except Exception:
        return ""


def parse_voice_command(command: str) -> str | None:
    """Map natural voice commands to supported scan actions."""
    if not command:
        return None

    normalized = command.lower().strip()
    website_keywords = ("website", "web", "site", "url")
    scan_keywords = ("scan", "start", "run", "begin", "go", "check", "analyze")

    if any(keyword in normalized for keyword in website_keywords) and any(
        keyword in normalized for keyword in scan_keywords
    ):
        return "website_scan"

    if any(keyword in normalized for keyword in scan_keywords):
        return "live_scan"

    return None


def build_voice_briefing(result: dict, packets: list[dict] | None, mode: str) -> str:
    """Build the spoken briefing text for the selected voice mode."""
    packets = packets or []
    severity = result.get("severity", {})
    threat_level = result.get("threat_level", "UNKNOWN")
    total_packets = result.get("total_packets", len(packets))
    total_violations = result.get("total_violations", 0)
    affected_devices = result.get("affected_devices", [])
    top_device = affected_devices[0] if affected_devices else None
    requested_sites = sorted(
        {
            packet.get("requested_site")
            for packet in packets
            if packet.get("requested_site")
        }
    )
    violation_types = result.get("violation_types", [])
    analysis = result.get("analysis", "No analysis available.")
    has_targeted_sites = bool(requested_sites)

    if has_targeted_sites:
        intro = "I’ve reviewed the latest website scan."
    else:
        intro = "I’ve reviewed the latest network scan."

    if mode == "Executive":
        return (
            f"{intro} Here’s the quick executive update. Threat level is {threat_level}. "
            f"We reviewed {total_packets} packets and found {total_violations} potential PCI related violations. "
            "The main takeaway is that this environment should be reviewed before it is treated as fully clean."
        )

    if mode == "Technical":
        return (
            f"{intro} Here’s the technical summary. Threat level is {threat_level}, with a severity score of "
            f"{severity.get('overall_score', 0)} out of 10. "
            f"We found {total_violations} violations across {total_packets} captured packets. "
            f"Top violation types include {', '.join(violation_types[:3]) if violation_types else 'none detected'}."
        )

    if mode == "Remediation":
        if top_device:
            return (
                f"{intro} Here’s the remediation priority. Start with device {top_device['ip']}, "
                f"which shows {top_device['violation_count']} violations. "
                "First review any insecure services, confirm whether the exposure is expected, and then work through the fix steps shown in the dashboard."
            )
        return (
            f"{intro} Here’s the remediation summary. Review the investigation guides, validate any insecure protocols, "
            "and prioritize the highest severity findings first."
        )

    if mode == "Website Scan":
        site_text = ", ".join(requested_sites) if requested_sites else "the selected websites"
        return (
            f"I’ve got the website scan results for {site_text}. "
            f"The system captured {total_packets} packets and found {total_violations} possible compliance issues. "
            "This gives us a focused view of the traffic generated by those specific web destinations."
        )

    first_paragraph = analysis.split("\n\n")[0].strip()
    if first_paragraph:
        return f"{intro} {first_paragraph}"
    return f"{intro} I have the analysis ready."


def infer_scan_type(packets: list[dict] | None) -> str:
    packets = packets or []
    if any(packet.get("requested_site") for packet in packets):
        return "Website Scan"
    return "Network Scan"


def build_risk_recommendation(result: dict, packets: list[dict] | None) -> str:
    packets = packets or []
    severity = result.get("severity", {})
    affected_devices = result.get("affected_devices", [])
    requested_sites = sorted(
        {
            packet.get("requested_site")
            for packet in packets
            if packet.get("requested_site")
        }
    )

    if severity.get("overall_score", 0) >= 8 and affected_devices:
        return (
            f"Prioritize immediate review of device {affected_devices[0]['ip']} and isolate any insecure services "
            "before the next validation cycle."
        )

    if requested_sites and result.get("total_violations", 0) > 0:
        return (
            "Re-run the targeted website scan after validating outbound traffic paths and confirm whether the flagged "
            "destinations are expected business activity."
        )

    if result.get("total_violations", 0) > 0:
        return "Review the investigation guides, validate the flagged protocols, and remediate the highest severity findings first."

    return "No urgent issues were detected. Document the clean result and keep scheduled scans running for continued assurance."

load_dotenv()

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(PROJECT_ROOT)
from analyzer.threat_engine import get_threat_summary


def load_voice_response_helper():
    voice_module_path = os.path.join(PROJECT_ROOT, "Voice Module", "voice_engine.py")
    if not os.path.exists(voice_module_path):
        return None

    if spec is None or spec.loader is None:
        return None

    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return (
        getattr(module, "get_voice_response", None),
        getattr(module, "VOICE_PROFILES", {}),
    )

IS_CLOUD = os.getenv("STREAMLIT_CLOUD", "false").lower() == "true"

st.set_page_config(
    page_title="Max-Guard Security Scanner",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
<style>
    .metric-card {
        background: #1e1e2e;
        border-radius: 10px;
        padding: 20px;
        border: 1px solid #333;
    }
    .violation-critical { color: #ff4444; font-weight: bold; }
    .violation-high { color: #ff8800; font-weight: bold; }
    .violation-medium { color: #ffcc00; font-weight: bold; }
    .violation-low { color: #4499ff; font-weight: bold; }
    .violation-none { color: #44ff88; font-weight: bold; }
    .section-header {
        border-left: 4px solid #3B8BD4;
        padding-left: 12px;
        margin: 20px 0 10px 0;
    }
    .assistant-note {
        background: linear-gradient(135deg, rgba(59,139,212,0.16), rgba(29,158,117,0.12));
        border: 1px solid rgba(59,139,212,0.35);
        border-radius: 14px;
        padding: 16px 18px;
        margin: 8px 0 16px 0;
    }
    .assistant-note-title {
        font-size: 0.9rem;
        letter-spacing: 0.04em;
        text-transform: uppercase;
        opacity: 0.8;
        margin-bottom: 8px;
    }
</style>
""", unsafe_allow_html=True)

st.title("🛡️ Max-Guard: PCI-DSS Network Security Scanner")
st.markdown("**AI-driven network security scanner for retail PCI-DSS compliance** | Sprint 2 | CCSU")
st.divider()

st.sidebar.image("https://img.shields.io/badge/Max--Guard-v1.0-blue", width=150)
st.sidebar.title("Scan Controls")
st.divider()
st.sidebar.subheader(" 🔊 Voice Assistance ")
voice_enabled = st.sidebar.toggle("Enable Siri-style Responses", value=True)
voice_mode = st.sidebar.selectbox(
    "Voice Briefing Type",
    ["Executive", "Technical", "Remediation", "Website Scan", "AI Summary"],
    index=0,
)
voice_persona = st.sidebar.selectbox(
    "Voice Persona",
    index=0,
    help="Choose how the spoken briefing should sound.",
)
st.sidebar.caption(
    "Voice keywords: `start scan`, `run scan`, `begin live scan`, "
    "`start website scan`, `scan websites`"
)
st.sidebar.caption(
    "Presentation-safe picks: Professional Female, Professional Male, Friendly Analyst. "
    "Use Light Humor or Angry Customer only if you want a playful demo moment."
)
manual_voice_refresh = st.sidebar.button(
    "Generate Voice Briefing",
    help="Generate or refresh the spoken briefing after a scan result is on screen.",
)
st.sidebar.markdown(f"**Mode:** {'☁️ Cloud' if IS_CLOUD else '💻 Local'}")
st.sidebar.divider()

def run_local_scan(packet_count):
    from scanner.sniffer import start_sniffing, captured_packets
    captured_packets.clear()
    with st.spinner(f"Scanning network... capturing {packet_count} packets"):
        start_sniffing(packet_count=packet_count)
    return captured_packets


def run_website_scan(packet_count, sites, timeout_seconds=15):
    from scanner.sniffer import start_sniffing, captured_packets

    normalized_sites = [site.strip() for site in sites if site.strip()]
    if not normalized_sites:
        raise ValueError("Enter at least one website URL or domain to scan.")

    captured_packets.clear()
    with st.spinner(f"Scanning website traffic for {', '.join(normalized_sites)}"):
        start_sniffing(
            packet_count=packet_count,
            sites=normalized_sites,
            timeout=timeout_seconds,
        )
    return captured_packets


def render_scan_error(exc: Exception) -> None:
    message = str(exc)
    if "/dev/bpf" in message or "Permission denied" in message:
        st.error(
            "Live packet capture on macOS needs elevated permissions. "
            "Run Streamlit with sudo, or run the scanner separately and upload scan_results.json."
        )
        st.code(
            "cd '/Users/jaidenwinborne/Desktop/Project Collective/Update4maxguard-main'\n"
            "sudo python3 -m streamlit run dashboard/app.py",
            language="bash",
        )
        return

    st.error(f"Scan failed: {exc}")

def load_packets_from_file(uploaded_file):
    content = uploaded_file.read().decode("utf-8")
    return json.loads(content)

def render_threat_badge(level):
    colors = {
        "CRITICAL": "#ff4444",
        "HIGH":     "#ff8800",
        "MEDIUM":   "#ffcc00",
        "LOW":      "#4499ff",
        "NONE":     "#44ff88"
    }
    color = colors.get(level, "#888888")
    st.markdown(f"""
    <div style="display:inline-block; background:{color}22; border:2px solid {color};
    border-radius:8px; padding:8px 24px; margin:10px 0;">
        <span style="color:{color}; font-size:24px; font-weight:bold;">
            {level}
        </span>
    </div>
    """, unsafe_allow_html=True)

def render_severity_gauge(score):
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=score,
        domain={"x": [0, 1], "y": [0, 1]},
        title={"text": "Severity Score", "font": {"size": 16}},
        gauge={
            "axis": {"range": [0, 10], "tickwidth": 1},
            "bar": {"color": "#3B8BD4"},
            "steps": [
                {"range": [0, 3],  "color": "#1a4a2e"},
                {"range": [3, 5],  "color": "#1a3a5c"},
                {"range": [5, 7],  "color": "#4a3a00"},
                {"range": [7, 9],  "color": "#4a2000"},
                {"range": [9, 10], "color": "#4a0000"},
            ],
            "threshold": {
                "line": {"color": "white", "width": 3},
                "thickness": 0.8,
                "value": score
            }
        }
    ))
    fig.update_layout(height=250, margin=dict(t=40, b=0, l=20, r=20),
                      paper_bgcolor="rgba(0,0,0,0)", font_color="white")
    st.plotly_chart(fig, use_container_width=True)

def render_overview_metrics(packets, result):
    col1, col2, col3, col4, col5 = st.columns(5)
    total = result["total_packets"]
    violations = result["total_violations"]
    rate = round((violations / total * 100), 1) if total > 0 else 0
    score = result["severity"]["overall_score"]
    devices = len(result["affected_devices"])

    col1.metric("Total Packets", total)
    col2.metric("PCI Violations", violations, delta=f"{rate}% of traffic" if violations > 0 else None, delta_color="inverse")
    col3.metric("Affected Devices", devices)
    col4.metric("Severity Score", f"{score}/10")
    col5.metric("Threat Level", result["threat_level"])


def render_scan_context_cards(packets, result):
    scan_type = infer_scan_type(packets)
    requested_sites = sorted(
        {
            packet.get("requested_site")
            for packet in packets
            if packet.get("requested_site")
        }
    )
    timestamps = [packet.get("timestamp") for packet in packets if packet.get("timestamp")]
    last_scan_time = max(timestamps) if timestamps else datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    recommendation = build_risk_recommendation(result, packets)

    col1, col2, col3, col4 = st.columns(4)
    col1.metric("Scan Type", scan_type)
    col2.metric("Target Sites", str(len(requested_sites)) if requested_sites else "0")
    col3.metric("Last Scan", last_scan_time)
    col4.metric("Next Action", "Review" if result["total_violations"] else "Monitor")

    if requested_sites:
        st.markdown(
            f"**Requested Sites:** {', '.join(requested_sites)}"
        )

    st.markdown(
        f"""
        <div class="assistant-note">
            <div class="assistant-note-title">Risk Recommendation</div>
            <div>{recommendation}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

def render_charts(packets, result):
    df = pd.DataFrame(packets)

    st.markdown('<div class="section-header"><h3>Traffic Analysis</h3></div>', unsafe_allow_html=True)

    col1, col2 = st.columns(2)

    with col1:
        if "protocol" in df.columns:
            protocol_counts = df["protocol"].value_counts().reset_index()
            protocol_counts.columns = ["Protocol", "Count"]
            fig = px.pie(
                protocol_counts, values="Count", names="Protocol",
                title="Protocol Distribution",
                color_discrete_sequence=["#3B8BD4", "#1D9E75", "#E8593C", "#9F6BDD"]
            )
            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font_color="white")
            st.plotly_chart(fig, use_container_width=True)

    with col2:
        render_severity_gauge(result["severity"]["overall_score"])

    col3, col4 = st.columns(2)

    with col3:
        if "timestamp" in df.columns:
            df["timestamp"] = pd.to_datetime(df["timestamp"])
            violations_df = df[df["pci_violation"] == True].copy()
            if not violations_df.empty:
                violations_df["minute"] = violations_df["timestamp"].dt.floor("s")
                timeline = violations_df.groupby("minute").size().reset_index(name="count")
                fig = px.line(
                    timeline, x="minute", y="count",
                    title="Violation Timeline",
                    labels={"minute": "Time", "count": "Violations"},
                    color_discrete_sequence=["#ff4444"]
                )
                fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font_color="white")
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("No violations to plot on timeline.")

    with col4:
        patterns = result.get("patterns", {})
        top_talkers = patterns.get("top_talkers", [])
        if top_talkers:
            talkers_df = pd.DataFrame(top_talkers)
            fig = px.bar(
                talkers_df, x="ip", y="count",
                title="Top Talkers (by packet count)",
                labels={"ip": "IP Address", "count": "Packets"},
                color="count",
                color_continuous_scale="Blues"
            )
            fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font_color="white")
            st.plotly_chart(fig, use_container_width=True)

    top_ports = patterns.get("top_ports", [])
    if top_ports:
        ports_df = pd.DataFrame(top_ports)
        fig = px.bar(
            ports_df, x="port", y="count",
            title="Top Destination Ports",
            labels={"port": "Port", "count": "Packet Count"},
            color="count",
            color_continuous_scale="Reds"
        )
        fig.update_layout(paper_bgcolor="rgba(0,0,0,0)", font_color="white")
        st.plotly_chart(fig, use_container_width=True)

def render_violations_table(packets):
    df = pd.DataFrame(packets)
    violations_df = df[df["pci_violation"] == True]
    if not violations_df.empty:
        st.markdown('<div class="section-header"><h3>PCI-DSS Violations Detected</h3></div>', unsafe_allow_html=True)
        st.dataframe(
            violations_df[["timestamp", "src_ip", "dst_ip", "protocol", "dst_port", "violation_detail"]],
            use_container_width=True
        )
    else:
        st.success("No PCI-DSS violations detected in this scan.")

def render_affected_devices(result):
    devices = result.get("affected_devices", [])
    if not devices:
        return
    st.markdown('<div class="section-header"><h3>Affected Devices</h3></div>', unsafe_allow_html=True)
    for device in devices:
        with st.expander(f"{device['ip']} — {device['device_type']} — {device['violation_count']} violations"):
            st.markdown(f"**IP Address:** `{device['ip']}`")
            st.markdown(f"**Device Type:** {device['device_type']}")
            st.markdown(f"**Total Violations:** {device['violation_count']}")
            st.markdown("**Violations Found:**")
            for v in device["violations"]:
                st.markdown(f"- {v}")

def render_investigation_guides(result):
    guides = result.get("investigation_guides", {})
    if not guides:
        return
    st.markdown('<div class="section-header"><h3>Investigation & Remediation Guides</h3></div>', unsafe_allow_html=True)
    st.markdown("Step-by-step guidance for each violation found in this scan.")
    for protocol, guide in guides.items():
        with st.expander(f"How to investigate and fix: {protocol}"):
            st.markdown(f"**PCI-DSS Requirement:** `{guide['pci_requirement']}`")
            st.divider()
            st.markdown("**What it is:**")
            st.info(guide["what_it_is"])
            st.markdown("**How to investigate:**")
            for step in guide["how_to_investigate"]:
                st.markdown(f"- {step}")
            st.markdown("**How to fix:**")
            for step in guide["how_to_fix"]:
                st.markdown(f"- {step}")

def render_ai_analysis(result):
    st.markdown('<div class="section-header"><h3>AI Threat Analysis (GPT-4o-mini)</h3></div>', unsafe_allow_html=True)
    render_threat_badge(result["threat_level"])
    st.markdown(result["analysis"])

def render_exports(packets, result):
    st.markdown('<div class="section-header"><h3>Export Reports</h3></div>', unsafe_allow_html=True)
    col1, col2, col3 = st.columns(3)

    with col1:
        json_str = json.dumps(packets, indent=2)
        st.download_button(
            label="Download scan_results.json",
            data=json_str,
            file_name=f"maxguard_scan_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json",
            mime="application/json"
        )

    with col2:
        violations = [p for p in packets if p.get("pci_violation")]
        if violations:
            output = io.StringIO()
            writer = csv.DictWriter(output, fieldnames=violations[0].keys())
            writer.writeheader()
            writer.writerows(violations)
            st.download_button(
                label="Download violations.csv",
                data=output.getvalue(),
                file_name=f"maxguard_violations_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv",
                mime="text/csv"
            )

    with col3:
        summary = f"""MAX-GUARD EXECUTIVE SUMMARY
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
{'='*50}

THREAT LEVEL: {result['threat_level']}
SEVERITY SCORE: {result['severity']['overall_score']}/10
TOTAL PACKETS: {result['total_packets']}
TOTAL VIOLATIONS: {result['total_violations']}

VIOLATIONS FOUND:
{chr(10).join(f'- {v}' for v in result['violation_types'])}

AFFECTED DEVICES:
{chr(10).join(f"- {d['ip']} ({d['device_type']}): {d['violation_count']} violations" for d in result['affected_devices'])}

FULL AI ANALYSIS:
{result['analysis']}
"""
        st.download_button(
            label="Download executive_summary.txt",
            data=summary,
            file_name=f"maxguard_executive_summary_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain"
        )

def display_results(packets):
    if not packets:
        st.warning("No packets captured.")
        st.session_state.latest_analysis = None
        st.session_state.latest_packets = None
        return

    with st.spinner("Running AI threat analysis..."):
        result = get_threat_summary(packets)
    st.session_state.result = result
    st.session_state.latest_analysis = result
    st.session_state.latest_packets = packets
    st.session_state.latest_scan_meta = {
        "scan_type": infer_scan_type(packets),
        "last_scan_time": max(
            [packet.get("timestamp") for packet in packets if packet.get("timestamp")],
            default=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ),
    }

    render_scan_context_cards(packets, result)
    st.divider()
    render_overview_metrics(packets, result)
    st.divider()
    render_charts(packets, result)
    st.divider()

    st.markdown('<div class="section-header"><h3>All Captured Packets</h3></div>', unsafe_allow_html=True)
    st.dataframe(pd.DataFrame(packets), use_container_width=True)
    st.divider()

    render_violations_table(packets)
    st.divider()
    render_affected_devices(result)
    st.divider()
    render_investigation_guides(result)
    st.divider()
    render_ai_analysis(result)
    st.divider()
    render_exports(packets, result)


def generate_voice_briefing() -> None:
    latest_result = st.session_state.get("latest_analysis")
    if not latest_result or not get_voice_response:
        return

    summary_text = build_voice_briefing(
        latest_result,
        st.session_state.get("latest_packets"),
        voice_mode,
    )
    st.session_state.latest_voice_text = summary_text
    audio_bytes = get_voice_response(
        summary_text,
        profile_name=voice_persona,
    )
    if not audio_bytes:
        raise ValueError("No audio bytes were returned from the voice service.")
    st.session_state.latest_voice_audio = audio_bytes

if IS_CLOUD:
    st.sidebar.markdown("### Upload Scan Results")
    uploaded_file = st.sidebar.file_uploader("Upload scan_results.json", type="json")
    if uploaded_file is not None:
        packets = load_packets_from_file(uploaded_file)
        st.success(f"Loaded {len(packets)} packets from file.")
        display_results(packets)
    else:
        st.info("Upload a scan_results.json file from the sidebar to begin analysis.")
else:
    st.sidebar.markdown("### Scan Settings")
    packet_count = st.sidebar.slider("Packets to capture", 10, 500, 100, step=10)
    website_input = st.sidebar.text_area(
        "Website URLs for targeted scan",
        value="https://google.com\nhttps://microsoft.com",
        help="Enter one website per line for a targeted website scan.",
    )
    if st.sidebar.button("Give Voice Command"):
        with st.spinner("Listening...."):
            cmd = listen_for_command()
        action = parse_voice_command(cmd)
        if action:
            st.sidebar.success(f"Command received: {cmd}")
            try:
                if action == "website_scan":
                    sites = website_input.splitlines()
                    packets = run_website_scan(packet_count, sites)
                else:
                    packets = run_local_scan(packet_count)
                display_results(packets)
            except Exception as exc:
                render_scan_error(exc)
        elif cmd:
            st.sidebar.warning(
                "Voice command not recognized. Try: start scan, run scan, "
                "start website scan, or scan websites."
            )
        else:
            st.sidebar.warning("No voice command detected.")
    st.sidebar.divider()
    st.sidebar.markdown("### Targeted Website Scan")
    if st.sidebar.button("Start Website Scan"):
        try:
            sites = website_input.splitlines()
            packets = run_website_scan(packet_count, sites)
            display_results(packets)
        except Exception as exc:
            render_scan_error(exc)
    st.sidebar.divider()
    st.sidebar.markdown("### Load Previous Scan")
    uploaded_file = st.sidebar.file_uploader("Upload scan_results.json", type="json")

    if uploaded_file is not None:
        packets = load_packets_from_file(uploaded_file)
        st.success(f"Loaded {len(packets)} packets from uploaded file.")
        display_results(packets)
    elif st.sidebar.button("Start Live Scan", type="primary"):
        try:
            packets = run_local_scan(packet_count)
            display_results(packets)
        except Exception as exc:
            render_scan_error(exc)
    else:
        st.markdown("""
        ### Welcome to Max-Guard
        **Two ways to use this dashboard:**
        - **Live Scan:** Click *Start Live Scan* in the sidebar to capture real network traffic
        - **Website Scan:** Enter site URLs and click *Start Website Scan* to capture targeted web traffic
        - **Upload Results:** Upload a previously saved `scan_results.json` file

        This tool scans your network for PCI-DSS v4.0 violations and uses GPT-4o-mini
        to generate a professional compliance analysis report.
        """)

latest_result = st.session_state.get("latest_analysis")
if voice_enabled and latest_result and get_voice_response and (
    manual_voice_refresh or not st.session_state.get("latest_voice_audio")
):
    try:
        with st.spinner("Generating voice briefing..."):
            generate_voice_briefing()
    except Exception as exc:
        st.warning(f"Voice playback unavailable right now: {exc}")

if voice_enabled and st.session_state.get("latest_voice_text"):
    st.markdown(
        f"""
        <div class="assistant-note">
            <div class="assistant-note-title">Voice Briefing Script</div>
            <div>{st.session_state["latest_voice_text"]}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

if voice_enabled and st.session_state.get("latest_voice_audio"):
    st.markdown("**Voice Playback**")
    st.audio(st.session_state["latest_voice_audio"], format="audio/mpeg")
    st.download_button(
        label="Download Voice Briefing",
        data=st.session_state["latest_voice_audio"],
        file_name="maxguard_voice_briefing.mp3",
        mime="audio/mpeg",
    )
